/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedSchedulesRouteImport } from './routes/_authed.schedules'
import { Route as AuthedRiskRouteImport } from './routes/_authed.risk'
import { Route as AuthedRequestsRouteImport } from './routes/_authed.requests'
import { Route as AuthedProcessesRouteImport } from './routes/_authed.processes'
import { Route as AuthedMyStatusRouteImport } from './routes/_authed.my-status'
import { Route as AuthedDownloadsRouteImport } from './routes/_authed.downloads'
import { Route as AuthedDomainsRouteImport } from './routes/_authed.domains'
import { Route as AuthedDevicesRouteImport } from './routes/_authed.devices'
import { Route as AuthedDeviceControlRouteImport } from './routes/_authed.device-control'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAutoResponseRouteImport } from './routes/_authed.auto-response'
import { Route as AuthedAlertsRouteImport } from './routes/_authed.alerts'
import { Route as AuthedActivityRouteImport } from './routes/_authed.activity'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesRoute = AuthedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRiskRoute = AuthedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProcessesRoute = AuthedProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyStatusRoute = AuthedMyStatusRouteImport.update({
  id: '/my-status',
  path: '/my-status',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDownloadsRoute = AuthedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsRoute = AuthedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesRoute = AuthedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeviceControlRoute = AuthedDeviceControlRouteImport.update({
  id: '/device-control',
  path: '/device-control',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAutoResponseRoute = AuthedAutoResponseRouteImport.update({
  id: '/auto-response',
  path: '/auto-response',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/alerts': typeof AuthedAlertsRoute
  '/auto-response': typeof AuthedAutoResponseRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/device-control': typeof AuthedDeviceControlRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/my-status': typeof AuthedMyStatusRoute
  '/processes': typeof AuthedProcessesRoute
  '/requests': typeof AuthedRequestsRoute
  '/risk': typeof AuthedRiskRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/alerts': typeof AuthedAlertsRoute
  '/auto-response': typeof AuthedAutoResponseRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/device-control': typeof AuthedDeviceControlRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/my-status': typeof AuthedMyStatusRoute
  '/processes': typeof AuthedProcessesRoute
  '/requests': typeof AuthedRequestsRoute
  '/risk': typeof AuthedRiskRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/settings': typeof AuthedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/auto-response': typeof AuthedAutoResponseRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/device-control': typeof AuthedDeviceControlRoute
  '/_authed/devices': typeof AuthedDevicesRoute
  '/_authed/domains': typeof AuthedDomainsRoute
  '/_authed/downloads': typeof AuthedDownloadsRoute
  '/_authed/my-status': typeof AuthedMyStatusRoute
  '/_authed/processes': typeof AuthedProcessesRoute
  '/_authed/requests': typeof AuthedRequestsRoute
  '/_authed/risk': typeof AuthedRiskRoute
  '/_authed/schedules': typeof AuthedSchedulesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/auto-response'
    | '/dashboard'
    | '/device-control'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/my-status'
    | '/processes'
    | '/requests'
    | '/risk'
    | '/schedules'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/auto-response'
    | '/dashboard'
    | '/device-control'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/my-status'
    | '/processes'
    | '/requests'
    | '/risk'
    | '/schedules'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/activity'
    | '/_authed/alerts'
    | '/_authed/auto-response'
    | '/_authed/dashboard'
    | '/_authed/device-control'
    | '/_authed/devices'
    | '/_authed/domains'
    | '/_authed/downloads'
    | '/_authed/my-status'
    | '/_authed/processes'
    | '/_authed/requests'
    | '/_authed/risk'
    | '/_authed/schedules'
    | '/_authed/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules': {
      id: '/_authed/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthedSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/risk': {
      id: '/_authed/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthedRiskRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/processes': {
      id: '/_authed/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthedProcessesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-status': {
      id: '/_authed/my-status'
      path: '/my-status'
      fullPath: '/my-status'
      preLoaderRoute: typeof AuthedMyStatusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/downloads': {
      id: '/_authed/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthedDownloadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains': {
      id: '/_authed/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthedDomainsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices': {
      id: '/_authed/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthedDevicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/device-control': {
      id: '/_authed/device-control'
      path: '/device-control'
      fullPath: '/device-control'
      preLoaderRoute: typeof AuthedDeviceControlRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auto-response': {
      id: '/_authed/auto-response'
      path: '/auto-response'
      fullPath: '/auto-response'
      preLoaderRoute: typeof AuthedAutoResponseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedAutoResponseRoute: typeof AuthedAutoResponseRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDeviceControlRoute: typeof AuthedDeviceControlRoute
  AuthedDevicesRoute: typeof AuthedDevicesRoute
  AuthedDomainsRoute: typeof AuthedDomainsRoute
  AuthedDownloadsRoute: typeof AuthedDownloadsRoute
  AuthedMyStatusRoute: typeof AuthedMyStatusRoute
  AuthedProcessesRoute: typeof AuthedProcessesRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
  AuthedRiskRoute: typeof AuthedRiskRoute
  AuthedSchedulesRoute: typeof AuthedSchedulesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedAutoResponseRoute: AuthedAutoResponseRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDeviceControlRoute: AuthedDeviceControlRoute,
  AuthedDevicesRoute: AuthedDevicesRoute,
  AuthedDomainsRoute: AuthedDomainsRoute,
  AuthedDownloadsRoute: AuthedDownloadsRoute,
  AuthedMyStatusRoute: AuthedMyStatusRoute,
  AuthedProcessesRoute: AuthedProcessesRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
  AuthedRiskRoute: AuthedRiskRoute,
  AuthedSchedulesRoute: AuthedSchedulesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
