/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWebhooksRouteImport } from './routes/_authed.webhooks'
import { Route as AuthedUsbRouteImport } from './routes/_authed.usb'
import { Route as AuthedTelemetryRouteImport } from './routes/_authed.telemetry'
import { Route as AuthedSettingsRouteImport } from './routes/_authed.settings'
import { Route as AuthedSchedulesRouteImport } from './routes/_authed.schedules'
import { Route as AuthedRiskRouteImport } from './routes/_authed.risk'
import { Route as AuthedRetentionRouteImport } from './routes/_authed.retention'
import { Route as AuthedRequestsRouteImport } from './routes/_authed.requests'
import { Route as AuthedProcessesRouteImport } from './routes/_authed.processes'
import { Route as AuthedPeripheralsRouteImport } from './routes/_authed.peripherals'
import { Route as AuthedOrganizationsRouteImport } from './routes/_authed.organizations'
import { Route as AuthedMyStatusRouteImport } from './routes/_authed.my-status'
import { Route as AuthedLiveStreamRouteImport } from './routes/_authed.live-stream'
import { Route as AuthedInsightsRouteImport } from './routes/_authed.insights'
import { Route as AuthedFilesRouteImport } from './routes/_authed.files'
import { Route as AuthedDownloadsRouteImport } from './routes/_authed.downloads'
import { Route as AuthedDomainsRouteImport } from './routes/_authed.domains'
import { Route as AuthedDevicesRouteImport } from './routes/_authed.devices'
import { Route as AuthedDeviceControlRouteImport } from './routes/_authed.device-control'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedBrowsingRouteImport } from './routes/_authed.browsing'
import { Route as AuthedBackupsRouteImport } from './routes/_authed.backups'
import { Route as AuthedAutoResponseRouteImport } from './routes/_authed.auto-response'
import { Route as AuthedAuditRouteImport } from './routes/_authed.audit'
import { Route as AuthedAlertsRouteImport } from './routes/_authed.alerts'
import { Route as AuthedActivityRouteImport } from './routes/_authed.activity'
import { Route as ApiPublicPurgeScreenshotsRouteImport } from './routes/api/public/purge-screenshots'
import { Route as ApiPublicDispatchWebhooksRouteImport } from './routes/api/public/dispatch-webhooks'
import { Route as ApiPublicCreateSnapshotRouteImport } from './routes/api/public/create-snapshot'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWebhooksRoute = AuthedWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsbRoute = AuthedUsbRouteImport.update({
  id: '/usb',
  path: '/usb',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTelemetryRoute = AuthedTelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSchedulesRoute = AuthedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRiskRoute = AuthedRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRetentionRoute = AuthedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProcessesRoute = AuthedProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPeripheralsRoute = AuthedPeripheralsRouteImport.update({
  id: '/peripherals',
  path: '/peripherals',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrganizationsRoute = AuthedOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMyStatusRoute = AuthedMyStatusRouteImport.update({
  id: '/my-status',
  path: '/my-status',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLiveStreamRoute = AuthedLiveStreamRouteImport.update({
  id: '/live-stream',
  path: '/live-stream',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInsightsRoute = AuthedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFilesRoute = AuthedFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDownloadsRoute = AuthedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsRoute = AuthedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesRoute = AuthedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeviceControlRoute = AuthedDeviceControlRouteImport.update({
  id: '/device-control',
  path: '/device-control',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBrowsingRoute = AuthedBrowsingRouteImport.update({
  id: '/browsing',
  path: '/browsing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBackupsRoute = AuthedBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAutoResponseRoute = AuthedAutoResponseRouteImport.update({
  id: '/auto-response',
  path: '/auto-response',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedActivityRoute = AuthedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiPublicPurgeScreenshotsRoute =
  ApiPublicPurgeScreenshotsRouteImport.update({
    id: '/api/public/purge-screenshots',
    path: '/api/public/purge-screenshots',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDispatchWebhooksRoute =
  ApiPublicDispatchWebhooksRouteImport.update({
    id: '/api/public/dispatch-webhooks',
    path: '/api/public/dispatch-webhooks',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCreateSnapshotRoute = ApiPublicCreateSnapshotRouteImport.update({
  id: '/api/public/create-snapshot',
  path: '/api/public/create-snapshot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/auto-response': typeof AuthedAutoResponseRoute
  '/backups': typeof AuthedBackupsRoute
  '/browsing': typeof AuthedBrowsingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/device-control': typeof AuthedDeviceControlRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/files': typeof AuthedFilesRoute
  '/insights': typeof AuthedInsightsRoute
  '/live-stream': typeof AuthedLiveStreamRoute
  '/my-status': typeof AuthedMyStatusRoute
  '/organizations': typeof AuthedOrganizationsRoute
  '/peripherals': typeof AuthedPeripheralsRoute
  '/processes': typeof AuthedProcessesRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/risk': typeof AuthedRiskRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/settings': typeof AuthedSettingsRoute
  '/telemetry': typeof AuthedTelemetryRoute
  '/usb': typeof AuthedUsbRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/api/public/create-snapshot': typeof ApiPublicCreateSnapshotRoute
  '/api/public/dispatch-webhooks': typeof ApiPublicDispatchWebhooksRoute
  '/api/public/purge-screenshots': typeof ApiPublicPurgeScreenshotsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/activity': typeof AuthedActivityRoute
  '/alerts': typeof AuthedAlertsRoute
  '/audit': typeof AuthedAuditRoute
  '/auto-response': typeof AuthedAutoResponseRoute
  '/backups': typeof AuthedBackupsRoute
  '/browsing': typeof AuthedBrowsingRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/device-control': typeof AuthedDeviceControlRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/files': typeof AuthedFilesRoute
  '/insights': typeof AuthedInsightsRoute
  '/live-stream': typeof AuthedLiveStreamRoute
  '/my-status': typeof AuthedMyStatusRoute
  '/organizations': typeof AuthedOrganizationsRoute
  '/peripherals': typeof AuthedPeripheralsRoute
  '/processes': typeof AuthedProcessesRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/risk': typeof AuthedRiskRoute
  '/schedules': typeof AuthedSchedulesRoute
  '/settings': typeof AuthedSettingsRoute
  '/telemetry': typeof AuthedTelemetryRoute
  '/usb': typeof AuthedUsbRoute
  '/webhooks': typeof AuthedWebhooksRoute
  '/api/public/create-snapshot': typeof ApiPublicCreateSnapshotRoute
  '/api/public/dispatch-webhooks': typeof ApiPublicDispatchWebhooksRoute
  '/api/public/purge-screenshots': typeof ApiPublicPurgeScreenshotsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/activity': typeof AuthedActivityRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/auto-response': typeof AuthedAutoResponseRoute
  '/_authed/backups': typeof AuthedBackupsRoute
  '/_authed/browsing': typeof AuthedBrowsingRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/device-control': typeof AuthedDeviceControlRoute
  '/_authed/devices': typeof AuthedDevicesRoute
  '/_authed/domains': typeof AuthedDomainsRoute
  '/_authed/downloads': typeof AuthedDownloadsRoute
  '/_authed/files': typeof AuthedFilesRoute
  '/_authed/insights': typeof AuthedInsightsRoute
  '/_authed/live-stream': typeof AuthedLiveStreamRoute
  '/_authed/my-status': typeof AuthedMyStatusRoute
  '/_authed/organizations': typeof AuthedOrganizationsRoute
  '/_authed/peripherals': typeof AuthedPeripheralsRoute
  '/_authed/processes': typeof AuthedProcessesRoute
  '/_authed/requests': typeof AuthedRequestsRoute
  '/_authed/retention': typeof AuthedRetentionRoute
  '/_authed/risk': typeof AuthedRiskRoute
  '/_authed/schedules': typeof AuthedSchedulesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/telemetry': typeof AuthedTelemetryRoute
  '/_authed/usb': typeof AuthedUsbRoute
  '/_authed/webhooks': typeof AuthedWebhooksRoute
  '/api/public/create-snapshot': typeof ApiPublicCreateSnapshotRoute
  '/api/public/dispatch-webhooks': typeof ApiPublicDispatchWebhooksRoute
  '/api/public/purge-screenshots': typeof ApiPublicPurgeScreenshotsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/audit'
    | '/auto-response'
    | '/backups'
    | '/browsing'
    | '/dashboard'
    | '/device-control'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/files'
    | '/insights'
    | '/live-stream'
    | '/my-status'
    | '/organizations'
    | '/peripherals'
    | '/processes'
    | '/requests'
    | '/retention'
    | '/risk'
    | '/schedules'
    | '/settings'
    | '/telemetry'
    | '/usb'
    | '/webhooks'
    | '/api/public/create-snapshot'
    | '/api/public/dispatch-webhooks'
    | '/api/public/purge-screenshots'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/activity'
    | '/alerts'
    | '/audit'
    | '/auto-response'
    | '/backups'
    | '/browsing'
    | '/dashboard'
    | '/device-control'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/files'
    | '/insights'
    | '/live-stream'
    | '/my-status'
    | '/organizations'
    | '/peripherals'
    | '/processes'
    | '/requests'
    | '/retention'
    | '/risk'
    | '/schedules'
    | '/settings'
    | '/telemetry'
    | '/usb'
    | '/webhooks'
    | '/api/public/create-snapshot'
    | '/api/public/dispatch-webhooks'
    | '/api/public/purge-screenshots'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/activity'
    | '/_authed/alerts'
    | '/_authed/audit'
    | '/_authed/auto-response'
    | '/_authed/backups'
    | '/_authed/browsing'
    | '/_authed/dashboard'
    | '/_authed/device-control'
    | '/_authed/devices'
    | '/_authed/domains'
    | '/_authed/downloads'
    | '/_authed/files'
    | '/_authed/insights'
    | '/_authed/live-stream'
    | '/_authed/my-status'
    | '/_authed/organizations'
    | '/_authed/peripherals'
    | '/_authed/processes'
    | '/_authed/requests'
    | '/_authed/retention'
    | '/_authed/risk'
    | '/_authed/schedules'
    | '/_authed/settings'
    | '/_authed/telemetry'
    | '/_authed/usb'
    | '/_authed/webhooks'
    | '/api/public/create-snapshot'
    | '/api/public/dispatch-webhooks'
    | '/api/public/purge-screenshots'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicCreateSnapshotRoute: typeof ApiPublicCreateSnapshotRoute
  ApiPublicDispatchWebhooksRoute: typeof ApiPublicDispatchWebhooksRoute
  ApiPublicPurgeScreenshotsRoute: typeof ApiPublicPurgeScreenshotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/webhooks': {
      id: '/_authed/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof AuthedWebhooksRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/usb': {
      id: '/_authed/usb'
      path: '/usb'
      fullPath: '/usb'
      preLoaderRoute: typeof AuthedUsbRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/telemetry': {
      id: '/_authed/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof AuthedTelemetryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedules': {
      id: '/_authed/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthedSchedulesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/risk': {
      id: '/_authed/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof AuthedRiskRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/retention': {
      id: '/_authed/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthedRetentionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/processes': {
      id: '/_authed/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthedProcessesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/peripherals': {
      id: '/_authed/peripherals'
      path: '/peripherals'
      fullPath: '/peripherals'
      preLoaderRoute: typeof AuthedPeripheralsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/organizations': {
      id: '/_authed/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthedOrganizationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/my-status': {
      id: '/_authed/my-status'
      path: '/my-status'
      fullPath: '/my-status'
      preLoaderRoute: typeof AuthedMyStatusRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/live-stream': {
      id: '/_authed/live-stream'
      path: '/live-stream'
      fullPath: '/live-stream'
      preLoaderRoute: typeof AuthedLiveStreamRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/insights': {
      id: '/_authed/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthedInsightsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/files': {
      id: '/_authed/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AuthedFilesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/downloads': {
      id: '/_authed/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthedDownloadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains': {
      id: '/_authed/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthedDomainsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices': {
      id: '/_authed/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthedDevicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/device-control': {
      id: '/_authed/device-control'
      path: '/device-control'
      fullPath: '/device-control'
      preLoaderRoute: typeof AuthedDeviceControlRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/browsing': {
      id: '/_authed/browsing'
      path: '/browsing'
      fullPath: '/browsing'
      preLoaderRoute: typeof AuthedBrowsingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/backups': {
      id: '/_authed/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof AuthedBackupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/auto-response': {
      id: '/_authed/auto-response'
      path: '/auto-response'
      fullPath: '/auto-response'
      preLoaderRoute: typeof AuthedAutoResponseRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/activity': {
      id: '/_authed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthedActivityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/public/purge-screenshots': {
      id: '/api/public/purge-screenshots'
      path: '/api/public/purge-screenshots'
      fullPath: '/api/public/purge-screenshots'
      preLoaderRoute: typeof ApiPublicPurgeScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dispatch-webhooks': {
      id: '/api/public/dispatch-webhooks'
      path: '/api/public/dispatch-webhooks'
      fullPath: '/api/public/dispatch-webhooks'
      preLoaderRoute: typeof ApiPublicDispatchWebhooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-snapshot': {
      id: '/api/public/create-snapshot'
      path: '/api/public/create-snapshot'
      fullPath: '/api/public/create-snapshot'
      preLoaderRoute: typeof ApiPublicCreateSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedActivityRoute: typeof AuthedActivityRoute
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedAutoResponseRoute: typeof AuthedAutoResponseRoute
  AuthedBackupsRoute: typeof AuthedBackupsRoute
  AuthedBrowsingRoute: typeof AuthedBrowsingRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDeviceControlRoute: typeof AuthedDeviceControlRoute
  AuthedDevicesRoute: typeof AuthedDevicesRoute
  AuthedDomainsRoute: typeof AuthedDomainsRoute
  AuthedDownloadsRoute: typeof AuthedDownloadsRoute
  AuthedFilesRoute: typeof AuthedFilesRoute
  AuthedInsightsRoute: typeof AuthedInsightsRoute
  AuthedLiveStreamRoute: typeof AuthedLiveStreamRoute
  AuthedMyStatusRoute: typeof AuthedMyStatusRoute
  AuthedOrganizationsRoute: typeof AuthedOrganizationsRoute
  AuthedPeripheralsRoute: typeof AuthedPeripheralsRoute
  AuthedProcessesRoute: typeof AuthedProcessesRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
  AuthedRetentionRoute: typeof AuthedRetentionRoute
  AuthedRiskRoute: typeof AuthedRiskRoute
  AuthedSchedulesRoute: typeof AuthedSchedulesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedTelemetryRoute: typeof AuthedTelemetryRoute
  AuthedUsbRoute: typeof AuthedUsbRoute
  AuthedWebhooksRoute: typeof AuthedWebhooksRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedActivityRoute: AuthedActivityRoute,
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedAutoResponseRoute: AuthedAutoResponseRoute,
  AuthedBackupsRoute: AuthedBackupsRoute,
  AuthedBrowsingRoute: AuthedBrowsingRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDeviceControlRoute: AuthedDeviceControlRoute,
  AuthedDevicesRoute: AuthedDevicesRoute,
  AuthedDomainsRoute: AuthedDomainsRoute,
  AuthedDownloadsRoute: AuthedDownloadsRoute,
  AuthedFilesRoute: AuthedFilesRoute,
  AuthedInsightsRoute: AuthedInsightsRoute,
  AuthedLiveStreamRoute: AuthedLiveStreamRoute,
  AuthedMyStatusRoute: AuthedMyStatusRoute,
  AuthedOrganizationsRoute: AuthedOrganizationsRoute,
  AuthedPeripheralsRoute: AuthedPeripheralsRoute,
  AuthedProcessesRoute: AuthedProcessesRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
  AuthedRetentionRoute: AuthedRetentionRoute,
  AuthedRiskRoute: AuthedRiskRoute,
  AuthedSchedulesRoute: AuthedSchedulesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedTelemetryRoute: AuthedTelemetryRoute,
  AuthedUsbRoute: AuthedUsbRoute,
  AuthedWebhooksRoute: AuthedWebhooksRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicCreateSnapshotRoute: ApiPublicCreateSnapshotRoute,
  ApiPublicDispatchWebhooksRoute: ApiPublicDispatchWebhooksRoute,
  ApiPublicPurgeScreenshotsRoute: ApiPublicPurgeScreenshotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
