/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRequestsRouteImport } from './routes/_authed.requests'
import { Route as AuthedDownloadsRouteImport } from './routes/_authed.downloads'
import { Route as AuthedDomainsRouteImport } from './routes/_authed.domains'
import { Route as AuthedDevicesRouteImport } from './routes/_authed.devices'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAlertsRouteImport } from './routes/_authed.alerts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDownloadsRoute = AuthedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDomainsRoute = AuthedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDevicesRoute = AuthedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAlertsRoute = AuthedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthedAlertsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/requests': typeof AuthedRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/alerts': typeof AuthedAlertsRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/devices': typeof AuthedDevicesRoute
  '/domains': typeof AuthedDomainsRoute
  '/downloads': typeof AuthedDownloadsRoute
  '/requests': typeof AuthedRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/alerts': typeof AuthedAlertsRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/devices': typeof AuthedDevicesRoute
  '/_authed/domains': typeof AuthedDomainsRoute
  '/_authed/downloads': typeof AuthedDownloadsRoute
  '/_authed/requests': typeof AuthedRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/alerts'
    | '/dashboard'
    | '/devices'
    | '/domains'
    | '/downloads'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/alerts'
    | '/_authed/dashboard'
    | '/_authed/devices'
    | '/_authed/domains'
    | '/_authed/downloads'
    | '/_authed/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/downloads': {
      id: '/_authed/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthedDownloadsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/domains': {
      id: '/_authed/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthedDomainsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/devices': {
      id: '/_authed/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthedDevicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/alerts': {
      id: '/_authed/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthedAlertsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAlertsRoute: typeof AuthedAlertsRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedDevicesRoute: typeof AuthedDevicesRoute
  AuthedDomainsRoute: typeof AuthedDomainsRoute
  AuthedDownloadsRoute: typeof AuthedDownloadsRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAlertsRoute: AuthedAlertsRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedDevicesRoute: AuthedDevicesRoute,
  AuthedDomainsRoute: AuthedDomainsRoute,
  AuthedDownloadsRoute: AuthedDownloadsRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
